export { default as Games } from "./Games";
export { default as Genres } from "./Genres";
export { default as Home } from "./Home";
export { default as GameCreate } from "./GameCreate";
export { default as GameDetails } from "./GameDetails";
export { default as GameEdit } from "./GameEdit";
export { default as Login } from "./Login";
export { default as GenreCreate } from "./GenreCreate";
export { default as GenreEdit } from "./GenreEdit";
