### Games
GET http://localhost:5050/games

###
GET http://localhost:5050/games/2

###
POST http://localhost:5050/games
Content-Type: multipart/form-data

{
    "name": "TEST GAME",
    "genreId": 2,
    "price": 100.00,
    "releaseDate": "2024-05-12"
}

###
PUT http://localhost:5050/games/2
Content-Type: application/json

{
    "name": "FC 26",
    "genreId": 5,
    "price": 29.99,
    "releaseDate": "2024-01-01"
}

###
DELETE http://localhost:5050/games/10

### Genres
GET http://localhost:5050/genres
