GET http://localhost:5235/games

###
GET http://localhost:5235/games/1

###
POST http://localhost:5235/games
Content-Type: application/json

{
    "name": "Valorant",
    "genreId": 1,
    "price": 10.00,
    "releaseDate": "2020-06-02"
}

###
PUT http://localhost:5235/games/7
Content-Type: application/json

{
    "name": "Counter Strike 2",
    "genre": "Competitive Shooter",
    "price": 15.00,
    "releaseDate": "2024-01-01"
}

###
DELETE http://localhost:5235/games/5
